package com.example.domain.mybatis;

public class IdTest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column id_test.id
     *
     * @mbggenerated Wed Jul 04 21:33:08 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column id_test.size
     *
     * @mbggenerated Wed Jul 04 21:33:08 CST 2018
     */
    private Integer size;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column id_test.id
     *
     * @return the value of id_test.id
     *
     * @mbggenerated Wed Jul 04 21:33:08 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column id_test.id
     *
     * @param id the value for id_test.id
     *
     * @mbggenerated Wed Jul 04 21:33:08 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column id_test.size
     *
     * @return the value of id_test.size
     *
     * @mbggenerated Wed Jul 04 21:33:08 CST 2018
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column id_test.size
     *
     * @param size the value for id_test.size
     *
     * @mbggenerated Wed Jul 04 21:33:08 CST 2018
     */
    public void setSize(Integer size) {
        this.size = size;
    }
}