package com.example.domain.mybatis;

public class PersonDemo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_demo.PERSON_ID
     *
     * @mbggenerated Wed Jul 04 21:33:08 CST 2018
     */
    private String personId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_demo.PERSON_NAME
     *
     * @mbggenerated Wed Jul 04 21:33:08 CST 2018
     */
    private String personName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_demo.PERSON_AGE
     *
     * @mbggenerated Wed Jul 04 21:33:08 CST 2018
     */
    private String personAge;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_demo.PERSON_ID
     *
     * @return the value of person_demo.PERSON_ID
     *
     * @mbggenerated Wed Jul 04 21:33:08 CST 2018
     */
    public String getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_demo.PERSON_ID
     *
     * @param personId the value for person_demo.PERSON_ID
     *
     * @mbggenerated Wed Jul 04 21:33:08 CST 2018
     */
    public void setPersonId(String personId) {
        this.personId = personId == null ? null : personId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_demo.PERSON_NAME
     *
     * @return the value of person_demo.PERSON_NAME
     *
     * @mbggenerated Wed Jul 04 21:33:08 CST 2018
     */
    public String getPersonName() {
        return personName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_demo.PERSON_NAME
     *
     * @param personName the value for person_demo.PERSON_NAME
     *
     * @mbggenerated Wed Jul 04 21:33:08 CST 2018
     */
    public void setPersonName(String personName) {
        this.personName = personName == null ? null : personName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_demo.PERSON_AGE
     *
     * @return the value of person_demo.PERSON_AGE
     *
     * @mbggenerated Wed Jul 04 21:33:08 CST 2018
     */
    public String getPersonAge() {
        return personAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_demo.PERSON_AGE
     *
     * @param personAge the value for person_demo.PERSON_AGE
     *
     * @mbggenerated Wed Jul 04 21:33:08 CST 2018
     */
    public void setPersonAge(String personAge) {
        this.personAge = personAge == null ? null : personAge.trim();
    }
}