package com.example.domain.mybatis;

public class UserInfo extends UserInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_pwd
     *
     * @mbggenerated Wed Jul 04 21:33:08 CST 2018
     */
    private String userPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_reg_time
     *
     * @mbggenerated Wed Jul 04 21:33:08 CST 2018
     */
    private String userRegTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_state
     *
     * @mbggenerated Wed Jul 04 21:33:08 CST 2018
     */
    private String userState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_log_in_time
     *
     * @mbggenerated Wed Jul 04 21:33:08 CST 2018
     */
    private String userLogInTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_class
     *
     * @mbggenerated Wed Jul 04 21:33:08 CST 2018
     */
    private String userClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_token
     *
     * @mbggenerated Wed Jul 04 21:33:08 CST 2018
     */
    private String userToken;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_pwd
     *
     * @return the value of user_info.user_pwd
     *
     * @mbggenerated Wed Jul 04 21:33:08 CST 2018
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_pwd
     *
     * @param userPwd the value for user_info.user_pwd
     *
     * @mbggenerated Wed Jul 04 21:33:08 CST 2018
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd == null ? null : userPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_reg_time
     *
     * @return the value of user_info.user_reg_time
     *
     * @mbggenerated Wed Jul 04 21:33:08 CST 2018
     */
    public String getUserRegTime() {
        return userRegTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_reg_time
     *
     * @param userRegTime the value for user_info.user_reg_time
     *
     * @mbggenerated Wed Jul 04 21:33:08 CST 2018
     */
    public void setUserRegTime(String userRegTime) {
        this.userRegTime = userRegTime == null ? null : userRegTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_state
     *
     * @return the value of user_info.user_state
     *
     * @mbggenerated Wed Jul 04 21:33:08 CST 2018
     */
    public String getUserState() {
        return userState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_state
     *
     * @param userState the value for user_info.user_state
     *
     * @mbggenerated Wed Jul 04 21:33:08 CST 2018
     */
    public void setUserState(String userState) {
        this.userState = userState == null ? null : userState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_log_in_time
     *
     * @return the value of user_info.user_log_in_time
     *
     * @mbggenerated Wed Jul 04 21:33:08 CST 2018
     */
    public String getUserLogInTime() {
        return userLogInTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_log_in_time
     *
     * @param userLogInTime the value for user_info.user_log_in_time
     *
     * @mbggenerated Wed Jul 04 21:33:08 CST 2018
     */
    public void setUserLogInTime(String userLogInTime) {
        this.userLogInTime = userLogInTime == null ? null : userLogInTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_class
     *
     * @return the value of user_info.user_class
     *
     * @mbggenerated Wed Jul 04 21:33:08 CST 2018
     */
    public String getUserClass() {
        return userClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_class
     *
     * @param userClass the value for user_info.user_class
     *
     * @mbggenerated Wed Jul 04 21:33:08 CST 2018
     */
    public void setUserClass(String userClass) {
        this.userClass = userClass == null ? null : userClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_token
     *
     * @return the value of user_info.user_token
     *
     * @mbggenerated Wed Jul 04 21:33:08 CST 2018
     */
    public String getUserToken() {
        return userToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_token
     *
     * @param userToken the value for user_info.user_token
     *
     * @mbggenerated Wed Jul 04 21:33:08 CST 2018
     */
    public void setUserToken(String userToken) {
        this.userToken = userToken == null ? null : userToken.trim();
    }
}