package com.example.dao;

import com.example.domain.mybatis.IdTest;
import org.springframework.stereotype.Repository;

@Repository
public interface IdTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_test
     *
     * @mbggenerated Wed Jul 04 21:33:08 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_test
     *
     * @mbggenerated Wed Jul 04 21:33:08 CST 2018
     */
    int insert(IdTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_test
     *
     * @mbggenerated Wed Jul 04 21:33:08 CST 2018
     */
    int insertSelective(IdTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_test
     *
     * @mbggenerated Wed Jul 04 21:33:08 CST 2018
     */
    IdTest selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_test
     *
     * @mbggenerated Wed Jul 04 21:33:08 CST 2018
     */
    int updateByPrimaryKeySelective(IdTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_test
     *
     * @mbggenerated Wed Jul 04 21:33:08 CST 2018
     */
    int updateByPrimaryKey(IdTest record);
}